import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { AntDesign } from '@expo/vector-icons';

const NewsContent = ({ route, navigation }) => {
  const { newsData, category } = route.params;

  const getDetailedContent = () => {
    // Add more detailed content based on the news category and ID
    switch(category) {
      case 'Exam Alerts':
        switch(newsData.id) {
          case 1:
            return [
              "Complete Analysis of CAT 2024 Slot 3 DILR Section:",
              "\nQuestion Paper Overview:",
              "• Total Questions: 24",
              "• Time Duration: 40 minutes",
              "• Difficulty Level: Moderate to High",
              "\nKey Topics Covered:",
              "• Data Interpretation Sets: 2",
              "• Logical Reasoning Sets: 2",
              "• Mixed DI-LR Set: 1",
              "\nDetailed Solutions:",
              "• Set 1: Market Analysis (6 questions)",
              "• Set 2: Puzzle on Team Formation (6 questions)",
              "• Set 3: Graph Interpretation (6 questions)",
              "• Set 4: Circular Arrangement (6 questions)",
              "\nDifficulty Analysis:",
              "• Easy Questions: 25%",
              "• Moderate Questions: 45%",
              "• Difficult Questions: 30%",
              "\nRecommended Approach:",
              "• Start with easier sets",
              "• Time management crucial",
              "• Accuracy over attempts",
              "\nDownload Resources:",
              "• Question Paper PDF",
              "• Detailed Solutions",
              "• Video Explanations",
              "\nExpert Tips:",
              "• Focus on accuracy",
              "• Practice similar patterns",
              "• Time management strategies",
              "\nPreparation Strategy:",
              "• Regular mock tests",
              "• Topic-wise practice",
              "• Previous year analysis"
            ];
          case 2:
            return [
              "GATE 2025 Admit Card Update:",
              "\nRevised Schedule:",
              "• Original Release Date: January 3, 2024",
              "• New Release Date: January 10, 2024",
              "• Exam Dates: Remain unchanged (February 3-11, 2024)",
              "\nReason for Postponement:",
              "• Technical upgrades in portal",
              "• Additional security features",
              "• Server capacity enhancement",
              "\nImportant Instructions:",
              "• Download from GOAPS portal",
              "• Valid ID proof mandatory",
              "• Reporting time: 2 hours before exam",
              "\nDocument Checklist:",
              "• Admit Card (colored print)",
              "• Valid Photo ID",
              "• Passport size photos",
              "• COVID self-declaration",
              "\nExam Day Guidelines:",
              "• Dress code compliance",
              "• Items allowed/prohibited",
              "• Social distancing norms",
              "\nHelpdesk Information:",
              "• Email support available",
              "• Phone support timings",
              "• Resolution timeline"
            ];
          case 3:
            return [
              "JEE Main 2025 Registration Extension:",
              "\nExtended Timeline:",
              "• Original Deadline: December 31, 2023",
              "• Extended Till: January 15, 2024",
              "• Late Fee Applicable: No",
              "\nRegistration Process:",
              "• Visit jeemain.nta.nic.in",
              "• Fill application form",
              "• Upload documents",
              "• Pay registration fee",
              "\nRequired Documents:",
              "• Class 10th certificate",
              "• Class 12th marksheet",
              "• Category certificate",
              "• PwD certificate (if applicable)",
              "\nApplication Fee:",
              "• General: ₹1000",
              "• EWS/OBC: ₹900",
              "• SC/ST/PwD: ₹800",
              "\nImportant Dates:",
              "• Form Submission: Till Jan 15",
              "• Fee Payment: Till Jan 16",
              "• Correction Window: Jan 18-20",
              "\nExam Schedule:",
              "• Session 1: Jan 24-31, 2024",
              "• Session 2: April 1-15, 2024",
              "\nHelpdesk Support:",
              "• 24x7 helpline numbers",
              "• Email assistance",
              "• Chat support"
            ];
          case 4:
            return [
              "NEET PG 2025 Application Process:",
              "\nApplication Timeline:",
              "• Start Date: January 2, 2024",
              "• End Date: January 31, 2024",
              "• Edit Window: February 5-7, 2024",
              "\nEligibility Criteria:",
              "• MBBS degree completion",
              "• Internship completion by March 31, 2025",
              "• Valid medical registration",
              "\nApplication Steps:",
              "• Registration on NBE portal",
              "• Document upload",
              "• Fee payment",
              "• Application submission",
              "\nExam Details:",
              "• Date: March 15, 2025",
              "• Duration: 3.5 hours",
              "• Questions: 200 MCQs",
              "\nDocument Requirements:",
              "• MBBS degree/provisional",
              "• Internship completion",
              "• Registration certificate",
              "• Category certificate",
              "\nFee Structure:",
              "• General/OBC: ₹4250",
              "• SC/ST/PwD: ₹3250",
              "\nCounselling Process:",
              "• Merit list preparation",
              "• Choice filling",
              "• Seat allocation",
              "• Document verification"
            ];
          case 5: // UPSC CSE 2025
            return [
              "UPSC CSE 2025 Notification Details:",
              "\nImportant Dates:",
              "• Notification Release: January 1, 2025",
              "• Registration Starts: January 2, 2025",
              "• Last Date: January 21, 2025",
              "• Prelims Exam: May 18, 2025",
              "\nVacancy Details:",
              "• IAS: 180 posts",
              "• IPS: 150 posts",
              "• IFS: 60 posts",
              "• Other Services: 610 posts",
              "\nEligibility Criteria:",
              "• Age Limit: 21-32 years",
              "• Educational Qualification: Graduate",
              "• Nationality: Indian Citizen",
              "\nApplication Process:",
              "• Online Registration at upsc.gov.in",
              "• Fee Payment: ₹100 (Exempt for SC/ST/PwD/Women)",
              "• Photo & Signature Upload",
              "• Document Submission",
              "\nExam Pattern:",
              "• Preliminary Examination",
              "  - GS Paper I (200 marks)",
              "  - CSAT Paper II (200 marks)",
              "• Main Examination",
              "  - 9 Papers (1750 marks)",
              "• Interview/Personality Test",
              "  - 275 marks",
              "\nPreparation Resources:",
              "• Detailed Syllabus",
              "• Previous Year Papers",
              "• Study Material Links",
              "• Online Test Series",
              "\nImportant Instructions:",
              "• Read notification carefully",
              "• Keep documents ready",
              "• Multiple applications not allowed",
              "• Check eligibility before applying"
            ];
          case 6: // XAT 2025
            return [
              "XAT 2025 Registration Update:",
              "\nRegistration Timeline:",
              "• Start Date: January 1, 2025",
              "• Regular Registration: Till November 30",
              "• Late Registration: December 10",
              "• Admit Card: December 20",
              "\nExam Details:",
              "• Exam Date: January 7, 2025",
              "• Duration: 3 hours 10 minutes",
              "• Mode: Computer Based Test",
              "• Centers: 80+ cities",
              "\nRegistration Fee:",
              "• Regular Fee: ₹2000",
              "• Late Fee: Additional ₹500",
              "• Payment Modes: Net Banking/Card",
              "\nParticipating Institutes:",
              "• XLRI Jamshedpur & Delhi",
              "• XIMB Bhubaneswar",
              "• IMT Ghaziabad",
              "• XIME Bangalore",
              "• Other 160+ B-schools",
              "\nExam Pattern Changes:",
              "• New Decision Making Section",
              "• Revised GK Format",
              "• Enhanced AR Questions",
              "• Essay Writing Component",
              "\nPreparation Guidelines:",
              "• Mock Test Series Available",
              "• Section-wise Strategy",
              "• Time Management Tips",
              "• Previous Papers Analysis",
              "\nSelection Process:",
              "• XAT Score",
              "• GD/PI/WAT",
              "• Academic Profile",
              "• Work Experience",
              "\nHelpdesk Support:",
              "• Email: xat@xlri.ac.in",
              "• Phone Support: 9 AM - 5 PM",
              "• Query Resolution: 48 hours"
            ];
          // Add cases for other news IDs
        }
        break;

      case 'College Alerts':
        switch(newsData.id) {
          case 1:
            return [
              "UCEED 2025 Admit Card Details:",
              "\nImportant Dates:",
              "• Admit Card Download: January 3, 2025",
              "• Last Date for Objections: January 8, 2025",
              "• Exam Date: January 20, 2025",
              "\nKey Instructions:",
              "• Download from official website",
              "• Check all details carefully",
              "• Carry valid ID proof",
              "\nExam Day Guidelines:",
              "• Reporting time: 8:30 AM",
              "• Documents required",
              "• COVID-19 protocols",
              "\nObjection Filing Process:",
              "• Login to candidate portal",
              "• Submit evidence",
              "• Pay required fee",
              "\nExam Pattern:",
              "• Part A: MCQs",
              "• Part B: Drawing",
              "• Total duration: 4 hours",
              "\nPreparation Tips:",
              "• Practice sketching",
              "• Solve previous papers",
              "• Time management",
              "\nImportant Documents:",
              "• Admit Card",
              "• Valid ID Proof",
              "• Photographs",
              "\nContact Information:",
              "• Helpdesk details",
              "• Email support",
              "• Emergency numbers"
            ];
          case 2:
            return [
              "IIT Delhi New Research Programs 2025:",
              "\nNew Programs Launched:",
              "• AI & Machine Learning Research",
              "• Sustainable Energy Solutions",
              "• Quantum Computing",
              "• Biomedical Engineering",
              "\nResearch Facilities:",
              "• State-of-art laboratories",
              "• High-performance computing center",
              "• Industry collaboration hub",
              "• International research partnerships",
              "\nEligibility Criteria:",
              "• PhD Programs: Masters in relevant field",
              "• Research Fellows: B.Tech/M.Tech",
              "• GATE/NET qualification",
              "• Minimum CGPA requirements",
              "\nFunding Options:",
              "• Institute fellowships",
              "• Government scholarships",
              "• Industry-sponsored projects",
              "• International grants",
              "\nApplication Process:",
              "• Online application submission",
              "• Research proposal",
              "• Interview rounds",
              "• Faculty interaction",
              "\nImportant Dates:",
              "• Application Start: February 2025",
              "• Deadline: March 2025",
              "• Interview Schedule: April 2025",
              "• Program Start: July 2025",
              "\nContact Information:",
              "• Academic Section: [Contact]",
              "• Department Coordinators",
              "• Research Cell",
              "• International Office"
            ];
          case 3:
            return [
              "MIT-WPU Admissions 2025:",
              "\nPrograms Offered:",
              "• Engineering: 12 branches",
              "• Management Studies",
              "• Law Programs",
              "• Liberal Arts",
              "• Design Programs",
              "\nAdmission Process:",
              "• Online Application",
              "• Entrance Test (MIT-WPU CET)",
              "• Personal Interview",
              "• Document Verification",
              "\nImportant Dates:",
              "• Application Start: January 2025",
              "• CET Dates: March-April 2025",
              "• Merit List: May 2025",
              "• Classes Begin: July 2025",
              "\nScholarship Details:",
              "• Merit-based scholarships",
              "• Sports quota",
              "• Cultural achievements",
              "• Research scholarships",
              "\nInfrastructure Highlights:",
              "• Smart classrooms",
              "• Research centers",
              "• Sports facilities",
              "• Innovation hub",
              "\nPlacement Statistics:",
              "• Average Package: 8.5 LPA",
              "• Highest Package: 42 LPA",
              "• 500+ Companies",
              "• International Placements",
              "\nContact Details:",
              "• Admission Helpline",
              "• Campus Address",
              "• Email Support",
              "• Social Media Handles"
            ];
          case 4:
            return [
              "VIT Scholarship Program 2025:",
              "\nScholarship Categories:",
              "• Merit Scholarships",
              "• Sports Excellence",
              "• Girl Child Support",
              "• Economically Weaker Sections",
              "\nEligibility Criteria:",
              "• Academic Performance: 85%+",
              "• VITEEE Rank Requirements",
              "• Sports Achievements",
              "• Family Income Criteria",
              "\nScholarship Benefits:",
              "• Full Tuition Fee Waiver",
              "• Partial Fee Waiver (25-75%)",
              "• Hostel Fee Concession",
              "• Research Support",
              "\nApplication Process:",
              "• Online Application",
              "• Document Submission",
              "• Interview Round",
              "• Final Selection",
              "\nRequired Documents:",
              "• Academic Certificates",
              "• Income Proof",
              "• Achievement Certificates",
              "• Identity Documents",
              "\nImportant Dates:",
              "• Application Start: March 2025",
              "• Submission Deadline: May 2025",
              "• Result Declaration: June 2025",
              "\nTerms & Conditions:",
              "• Minimum CGPA Maintenance",
              "• Regular Attendance",
              "• No Backlogs",
              "• Yearly Renewal Process"
            ];
          case 5:
            return [
              "BITS Pilani Campus Expansion Project:",
              "\nNew Infrastructure:",
              "• Advanced Research Centers",
              "• Innovation Labs",
              "• Smart Classrooms",
              "• Student Housing",
              "\nAcademic Expansion:",
              "• New Course Programs",
              "• Research Facilities",
              "• International Collaborations",
              "• Industry Partnerships",
              "\nProject Timeline:",
              "• Phase 1: January-June 2025",
              "• Phase 2: July-December 2025",
              "• Phase 3: 2026 Implementation",
              "\nNew Facilities:",
              "• Central Library Extension",
              "• Sports Complex",
              "• Innovation Center",
              "• Incubation Hub",
              "\nCapacity Enhancement:",
              "• Student Intake: +30%",
              "• Faculty Recruitment",
              "• Research Positions",
              "• Support Staff",
              "\nFunding Details:",
              "• Total Investment: ₹500 Cr",
              "• Government Grants",
              "• Alumni Contributions",
              "• Industry Funding",
              "\nImpact Assessment:",
              "• Academic Quality",
              "• Research Output",
              "• Student Experience",
              "• Global Rankings"
            ];
          case 6:
            return [
              "NIT Trichy Research Collaboration:",
              "\nCollaboration Details:",
              "• International Universities",
              "• Research Institutes",
              "• Industry Partners",
              "• Government Organizations",
              "\nResearch Areas:",
              "• Renewable Energy",
              "• AI & Robotics",
              "• Nanotechnology",
              "• Smart Manufacturing",
              "\nFunding Sources:",
              "• International Grants",
              "• Government Funding",
              "• Industry Sponsorship",
              "• Institute Resources",
              "\nOpportunities:",
              "• Student Exchange",
              "• Faculty Exchange",
              "• Joint Research",
              "• Technology Transfer",
              "\nEligibility Criteria:",
              "• Research Students",
              "• Faculty Members",
              "• Industry Partners",
              "• International Scholars",
              "\nApplication Process:",
              "• Proposal Submission",
              "• Review Process",
              "• Selection Criteria",
              "• Documentation",
              "\nTimeline:",
              "• Proposal Deadline: March 2025",
              "• Review Period: April 2025",
              "• Project Start: June 2025",
              "\nContact Information:",
              "• Research Office",
              "• International Relations",
              "• Department Coordinators"
            ];
        }
        break;

      case 'Admission Alerts':
        switch(newsData.id) {
          case 1: // AMUEEE 2025
            return [
              "AMUEEE 2025 Registration Details:",
              "\nImportant Dates:",
              "• Registration Start: January 3, 2025",
              "• Last Date: February 15, 2025",
              "• Admit Card: March 2025",
              "• Exam Date: April 2025",
              "\nCourses Offered:",
              "• B.Tech (8 branches)",
              "• B.Arch",
              "• B.E Programs",
              "• Dual Degree Options",
              "\nEligibility Criteria:",
              "• 10+2 with PCM",
              "• Minimum 60% aggregate",
              "• Age limit: 25 years",
              "\nApplication Process:",
              "• Online Registration",
              "• Fee Payment",
              "• Document Upload",
              "• Form Submission",
              "\nExam Pattern:",
              "• Physics: 50 questions",
              "• Chemistry: 50 questions",
              "• Mathematics: 50 questions",
              "• Total Marks: 300",
              "\nFee Structure:",
              "• Application Fee: ₹800 (Gen)",
              "• ₹400 (SC/ST/PwD)",
              "• Multiple Course Options",
              "\nRequired Documents:",
              "• Class 10th Certificate",
              "• Class 12th Marksheet",
              "• Category Certificate",
              "• Recent Photographs"
            ];

          case 2: // DU CUET
            return [
              "DU CUET 2025 Registration Update:",
              "\nRegistration Timeline:",
              "• Start Date: January 2, 2025",
              "• End Date: February 28, 2025",
              "• Exam: April-May 2025",
              "\nPrograms Available:",
              "• Arts & Humanities",
              "• Commerce",
              "• Sciences",
              "• Languages",
              "\nParticipating Colleges:",
              "• 90+ DU Colleges",
              "• 2000+ Programs",
              "• Multiple Campus Options",
              "\nEligibility:",
              "• 12th Pass from recognized board",
              "• Subject-specific criteria",
              "• No age limit",
              "\nExam Pattern:",
              "• Domain Knowledge Tests",
              "• General Test",
              "• Language Tests",
              "• Subject Combinations",
              "\nApplication Process:",
              "• NTA Portal Registration",
              "• Document Upload",
              "• Payment of Fees",
              "• College/Course Selection",
              "\nImportant Instructions:",
              "• Check eligibility carefully",
              "• Multiple subject selection",
              "• Preference filling",
              "• Merit list process"
            ];

          case 3: // IIIT Delhi
            return [
              "IIIT Delhi BTech Admissions 2025:",
              "\nPrograms Offered:",
              "• Computer Science & Engineering",
              "• Electronics & Communications",
              "• Information Technology",
              "• AI & Data Science",
              "\nAdmission Criteria:",
              "• JEE Main 2025 Score",
              "• Delhi Region Quota",
              "• Outside Delhi Quota",
              "• IIITD Merit List",
              "\nImportant Dates:",
              "• Application Start: April 2025",
              "• Last Date: June 2025",
              "• Counselling: July 2025",
              "\nEligibility Criteria:",
              "• 12th with PCM: 80%",
              "• JEE Main Cutoff",
              "• Age Requirements",
              "\nFee Structure:",
              "• Tuition Fee: ₹2.5L/year",
              "• Hostel Fee: ₹1L/year",
              "• Scholarships Available",
              "\nPlacement Statistics:",
              "• Average Package: 18 LPA",
              "• Highest Package: 45 LPA",
              "• 100% Placement",
              "\nCampus Facilities:",
              "• World-class Infrastructure",
              "• Research Labs",
              "• Innovation Centers",
              "• Sports Complex"
            ];

          case 4: // IIM CAT Results
            return [
              "IIM CAT 2024 Results Analysis:",
              "\nResult Statistics:",
              "• Total Appeared: 2.5L candidates",
              "• 99 percentile: Above 180",
              "• Gender Diversity: 38% female",
              "• Sectional Details Available",
              "\nToppers Analysis:",
              "• Highest Score: 235/300",
              "• Engineering Background: 76%",
              "• Non-Engineering: 24%",
              "• Work Experience Stats",
              "\nSelection Process:",
              "• Shortlisting Criteria",
              "• WAT-PI Schedule",
              "• Document Verification",
              "• Final Merit List",
              "\nIIM Calls:",
              "• IIM A: 99.5+ percentile",
              "• IIM B: 99+ percentile",
              "• IIM C: 99+ percentile",
              "• Other IIMs criteria",
              "\nImportant Dates:",
              "• WAT-PI: Feb-March 2025",
              "• Merit List: April 2025",
              "• Fee Payment: May 2025",
              "\nPreparation Tips:",
              "• Interview Preparation",
              "• GD Topics",
              "• WAT Strategies",
              "• Profile Building"
            ];

          case 5: // NIFT 2025
            return [
              "NIFT 2025 Application Process:",
              "\nPrograms Available:",
              "• Fashion Design",
              "• Accessory Design",
              "• Communication Design",
              "• Fashion Management",
              "\nApplication Timeline:",
              "• Start Date: January 1, 2025",
              "• Last Date: January 31, 2025",
              "• Exam Date: February 2025",
              "\nEligibility Criteria:",
              "• 12th Pass: Any Stream",
              "• Minimum 50% Marks",
              "• No Age Limit",
              "\nExam Pattern:",
              "• CAT (Creative Ability Test)",
              "• GAT (General Ability Test)",
              "• Situation Test",
              "• Interview",
              "\nDocument Requirements:",
              "• Academic Certificates",
              "• Portfolio (if applicable)",
              "• ID Proof",
              "• Category Certificates",
              "\nFee Details:",
              "• Application: ₹3000",
              "• Program Fee Structure",
              "• Scholarship Options",
              "\nCampus Options:",
              "• 17 NIFT Campuses",
              "• Specialization Choices",
              "• Infrastructure Details"
            ];

          case 6: // ISI Admission
            return [
              "ISI Admission Test 2025 Details:",
              "\nPrograms Offered:",
              "• B.Stat (Hons)",
              "• B.Math (Hons)",
              "• M.Stat",
              "• M.Math",
              "\nTest Schedule:",
              "• Application: January 2025",
              "• Exam Date: May 2025",
              "• Results: June 2025",
              "\nEligibility:",
              "• Academic Requirements",
              "• Stream-specific Criteria",
              "• Age Limitations",
              "\nExam Pattern:",
              "• Mathematics Focus",
              "• Statistical Reasoning",
              "• Logical Thinking",
              "• Multiple Choice Format",
              "\nPreparation Guide:",
              "• Syllabus Overview",
              "• Sample Papers",
              "• Study Materials",
              "• Important Topics",
              "\nAdmission Process:",
              "• Online Application",
              "• Document Verification",
              "• Interview Round",
              "• Final Selection",
              "\nCampus Life:",
              "• Research Environment",
              "• Library Facilities",
              "• Hostel Accommodation",
              "• Career Prospects"
            ];
        }
        break;

      // Add cases for other categories
    }
  };

  return (
    <ScrollView style={styles.container}>
      <TouchableOpacity 
        style={styles.backButton}
        onPress={() => navigation.goBack()}
      >
        <AntDesign name="arrowleft" size={24} color="#FFA500" />
      </TouchableOpacity>

      <View style={styles.authorContainer}>
        <AntDesign name="user" size={16} color="#FFA500" />
        <Text style={styles.authorText}>Author: Sudhanshu Singh</Text>
      </View>

      <View style={styles.headerContainer}>
        <Text style={styles.category}>{category}</Text>
        <Text style={styles.date}>{newsData.date}</Text>
      </View>

      <Text style={styles.title}>{newsData.title}</Text>
      
      <View style={styles.contentContainer}>
        {getDetailedContent()?.map((item, index) => (
          <Text key={index} style={styles.contentText}>{item}</Text>
        ))}
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  backButton: {
    padding: 16,
  },
  authorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#f8f9fa',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  authorText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 8,
    textAlign: 'justify',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  category: {
    fontSize: 14,
    color: '#FFA500',
    fontWeight: '500',
  },
  date: {
    fontSize: 14,
    color: '#666',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginVertical: 16,
    paddingHorizontal: 16,
    lineHeight: 32,
  },
  contentContainer: {
    padding: 16,
  },
  contentText: {
    fontSize: 16,
    color: '#444',
    marginBottom: 12,
    lineHeight: 24,
    textAlign: 'justify',
  },
});

export default NewsContent; 